#!/bin/bash

echo "🚀 Deploying RecallApp-Web to Vercel"
echo "===================================="
echo ""
echo "This script will help you deploy the RecallApp-Web to Vercel."
echo ""
echo "Prerequisites:"
echo "1. You need a Vercel account (free at https://vercel.com)"
echo "2. Vercel CLI is already installed"
echo ""
echo "Steps to deploy:"
echo ""
echo "1. First, login to Vercel:"
echo "   Run: vercel login"
echo ""
echo "2. After logging in, deploy the app:"
echo "   Run: vercel --prod"
echo ""
echo "3. Follow the prompts:"
echo "   - Set up and deploy: Yes"
echo "   - Which scope: Select your account"
echo "   - Link to existing project?: No (for first time)"
echo "   - Project name: recall-app (or your preferred name)"
echo "   - Directory: ./ (current directory)"
echo "   - Override settings?: No"
echo ""
echo "Alternative: One-command deployment after login:"
echo "   vercel --yes --prod"
echo ""
echo "📝 Notes:"
echo "- The app will be deployed with serverless Python functions"
echo "- Environment variables can be set in Vercel dashboard"
echo "- The deployment URL will be provided after completion"
echo ""
echo "Press Enter to start the deployment process..."
read

# Step 1: Login
echo "Step 1: Logging in to Vercel..."
vercel login

echo ""
echo "Step 2: Deploying to production..."
echo "Running: vercel --prod"
vercel --prod

echo ""
echo "✅ Deployment complete!"
echo "Check your deployment at the provided URL"
echo ""
echo "To redeploy after changes:"
echo "  vercel --prod"
echo ""
echo "To add environment variables:"
echo "  vercel env add"